#ifndef __HYDRO_PINOUT_H__
#define __HYDRO_PINOUT_H__

#define HYDRO_PINOUT_I2C0_SDA (11)
#define HYDRO_PINOUT_I2C0_SCL (12)

#define HYDRO_PINOUT_I2C1_SDA (13)
#define HYDRO_PINOUT_I2C1_SCL (14)

#define HYDRO_PINOUT_PUMP (38)

#define HYDRO_PINOUT_PWM (1)

#endif // __HYDRO_PINOUT_H__