#ifndef __HYDRO_PINOUT_H__
#define __HYDRO_PINOUT_H__

#define HYDRO_PINOUT_I2C0_SDA (9)
#define HYDRO_PINOUT_I2C0_SCL (10)

#define HYDRO_PINOUT_I2C1_SDA (11)
#define HYDRO_PINOUT_I2C1_SCL (12)

#endif // __HYDRO_PINOUT_H__